### PR TITLE
Fix tests in Node 6.5.0 by handling `fn` test name

### LINKED ISSUE #1027: Fix tests on Node.js 6.5.0
From https://github.com/avajs/ava/pull/1024#issuecomment-243609090. They passed on 6.4.0, but something changed.

### PR DESCRIPTION
**Pull request by sotojuan**
Attempts to fix #1027—feel free to close/discuss a better solution.

Node 6.5.0 uses a newer version of the v8 engine that is a bit smarter in figuring out the name of a function. Therefore, some tests were breaking because we presumed `test.name` to be a falsy value, and now it's `'fn'`. This PR handles `'fn'` the same way it handles a falsy function name value. While it fixes the breaking tests, it may not be the best choice in the long term.

### CODE REVIEW

File: lib/test-collection.js [hunk 1]
```diff
@@ -52,7 +52,7 @@ TestCollection.prototype.add = function (test) {
 		test.title = null;
 	}
 
-	if (!test.title) {
+	if (!test.title || test.title === 'fn') {
```
Comment (sindresorhus) [inline lib/test-collection.js]: What if the user names their test or function `fn`?

Comment (sotojuan) [inline lib/test-collection.js]: Yeah, that's the issue. I'm trying to think of a way that we can handle both falsy values and the test's function names but that also won't affect anyone else :/

**Comment by sotojuan** [comment]
@sindresorhus, what do you think is the best way to go forward with this?

**Comment by kevva** [comment]
> If nothing else, we can just check for Node versions...

If the purpose is to fix the test, I would just check the Node version in the test and assert accordingly.

**Comment by kevva** [comment]
I think this was added in V8 `5.1.39`. These links might be worth reading:

https://bugs.chromium.org/p/v8/issues/detail?id=3699
https://bugs.chromium.org/p/chromium/issues/detail?id=588803

**Comment by sotojuan** [comment]
Yeah it depends on the purpose—I feel like it's just to fix the test right? So it'd make sense to rollback the code changes and maybe have a test for Node versions before and after the change?

**Comment by kevva** [comment]
Yup, sounds good to me. Especially since this is a feature in ES2015 and not something we want to circumvent.

**Comment by sotojuan** [comment]
All right, so it's kinda hacky and it introduces a new dependency, but it works. Let me know what you think!

**Comment by fearphage** [comment]
Why not feature test it instead? 

```js
var supportsFunctionNames = (function testing() {}).name === 'testing';
```

This has the benefit of working in every environment consistently. Imagine if this feature were to be broken in v6.6 or removed in the future, the tests would always know how to do the right thing.

**Comment by sotojuan** [comment]
@fearphage Great idea. I've updated the code to do this with the existing `noop` function in the file.

**Comment by sotojuan** [comment]
I'm gonna go ahead and merge this since it's dev-only and the latest code changes have no negative or breaking effects.
