### PR TITLE
Make `t.log()` behave like `console.log()`

### LINKED ISSUE #1635: Make t.log() behave like console.log()
## Description

When using `--tap` output, trying to log an object results in an error.  Worse, the stack trace points to ava internals, not to my test code.

If `t.log` is given an object:

* Minimum expected behavior: Throw immediately
* Preferred expected behavior: Pass through `JSON.stringify(arg, null, 2)`

I do a lot of `t.log(JSON.stringify(resp.body, null, 2));` and it would be great to just say `t.log(resp.body);` instead.

### Test Source

```js
import { serial as test } from 'ava';

test('Log an object', (t) => {
  const myObject = { a: 1 };
  t.log(myObject);
  t.is(true, true);
});
```

### Error Message & Stack Trace

```
^^/d/o/b/ava >>> ava --tap test.js 

/Users/redacted/dev/oss/bug-reports/ava/node_modules/indent-string/index.js:9
		throw new TypeError(`Expected \`input\` to be a \`string\`, got \`${typeof str}\``);
		^

TypeError: Expected `input` to be a `string`, got `object`
    at module.exports (/Users/redacted/dev/oss/bug-reports/ava/node_modules/indent-string/index.js:9:9)
    at test.logs.forEach.log (/Users/redacted/dev/oss/bug-reports/ava/node_modules/ava/lib/reporters/tap.js:64:23)
    at Array.forEach (<anonymous>)
    at appendLogs (/Users/redacted/dev/oss/bug-reports/ava/node_modules/ava/lib/reporters/tap.js:63:15)
    at TapReporter.test (/Users/redacted/dev/oss/bug-reports/ava/node_modules/ava/lib/reporters/tap.js:83:4)
    at Logger.test (/Users/redacted/dev/oss/bug-reports/ava/node_modules/ava/lib/logger.js:27:28)
    at emitTwo (events.js:126:13)
    at RunStatus.emit (events.js:214:7)
    at RunStatus.handleTest (/Users/redacted/dev/oss/bug-reports/ava/node_modules/ava/lib/run-status.js:105:8)
    at emitOne (events.js:121:20)
    at ChildProcess.emit (events.js:211:7)
    at ChildProcess.ps.on.event (/Users/redacted/dev/oss/bug-reports/ava/node_modules/ava/lib/fork.js:79:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
```

### Config

N/A.  Here's my test package.json:

```json
{
  "name": "ava-bug-report",
  "version": "1.0.0",
  "description": "Reporting an issue in ava",
  "main": "test.js",
  "author": "Ed Brannin",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "ava": "^0.24.0"
  }
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava --tap test.js
```

## Relevant Links

https://github.com/edbrannin/ava-issue-1635

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v8.9.0
darwin 16.7.0
0.24.0
5.6.0
```

### PR DESCRIPTION
**Pull request by kugtong33**
Fixes #1635 

Use concordance to format all arguments except string arguments as the existing test will fail and I find it awkward this way. Update test to cater `t.log()` and `t.log(n1, n2, n3, ...)`.

### CODE REVIEW

File: lib/assert.js [hunk 1]
```diff
@@ -122,8 +122,15 @@ function wrapAssertions(callbacks) {
 			}
 		},
 
-		log(text) {
-			log(this, text);
+		log(...args) {
```
Comment (novemberborn) [inline lib/assert.js]: For the next few months we're still targeting Node.js 4, which doesn't support rest parameters. You'll have to use plain old `arguments` instead.

File: lib/assert.js [hunk 2]
```diff
@@ -122,8 +122,16 @@ function wrapAssertions(callbacks) {
...
 		},
 
-		log(text) {
-			log(this, text);
+		log() {
+			const args = Array.prototype.slice.call(arguments);
+			args.forEach((value, index) => {
+				args[index] = typeof value === 'string' ?
+					value : concordance.format(value, concordanceOptions);
+			});
```
Comment (novemberborn) [inline lib/assert.js]: Since you're really mapping `args` anyway this would be better as:

```js
const args = Array.from(arguments, value => {
  // ...
});
```

Comment (kugtong33) [reply lib/assert.js]: that makes sense! I was trying to find a better way :)

**Comment by novemberborn** [comment]
Thanks @kugtong33!
