### PR TITLE
Store an error object in AssertionError rather than a stack trace

### LINKED ISSUE #1399: Explore storing an error object, rather than directly capturing a stack trace
[Issuehunt badges](https://issuehunt.io/r/avajs/ava/issues/1399)

For asynchronous assertions we capture a stack trace before the assertion is run. Inspired by this comment by @alxandr we should explore storing an error object, and reading the stack trace later if it's actually necessary:

> … instead of passing the stack trace itself, an error object could be passed. This has less performance impact, because then the stack trace is only generated on demand (this might even be something that could improve the performance of your existing async tests).

See [`lib/test.js`](https://github.com/avajs/ava/blob/f6a7b18ad26d988fc85ce51892fd55ce4329edad/lib/test.js#L18) and [`lib/assert.js`](https://github.com/avajs/ava/blob/f6a7b18ad26d988fc85ce51892fd55ce4329edad/lib/assert.js#L32).

> There is a $40.00 open bounty on this issue. Add more on [Issuehunt](https://issuehunt.io/r/avajs/ava/issues/1399).
> - Checkout the [Issuehunt explorer](https://issuehunt.io/r/avajs/ava/) to discover more funded issues.
> - Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on Issuehunt to raise funds.

### PR DESCRIPTION
**Pull request by mihai-dinu**
Fixes #1399.

My idea was to always try to pass a new `Error` object in the AssertionError instead of a `stack` string. It might be a bit more memory inefficient, but it would allow for a more consistent behavior overall.
I then expose the `savedError`'s stack when `serializeError` is called.
One thing that I'm not too sure about is the `Error.stackTraceLimit` of the new Error object. I'm not sure if it takes effect when calling `new Error()` or at the point of getting the stack from the `savedError`. I would assume the first case applies. If that's the case, I can do the `Error.stackTraceLimit` "dance" before creating the new Error. 

The changes need to be unit tested and I will do that as well in this PR, but I first wanted someone to take a quick look over the changes and let me know if I should continue down this path or not.

### CODE REVIEW

**Comment by novemberborn** [comment]
Looks good @mihai-dinu. I assume you've seen the discussion in https://github.com/avajs/ava/pull/2008, which was the previous attempt at resolving this?

**Comment by mihai-dinu** [comment]
Yes, I've seen the comments in #2008. Did I miss anything there? I will start updating the tests and fixing the linting issues. 

Btw, I was thinking of opening another PR for Prettier support since I don't really like changing my IDE's tabs to actual tabs instead of spaces and having to put semicolon at the end of each line. Plus, you get consistent code formatting all over the project.

**Comment by mihai-dinu** [comment]
This PR is ready for review. Not sure what unit test I could add for the changes since they're mainly covered by the existing ones.

**Comment by novemberborn** [comment]
> Btw, I was thinking of opening another PR for Prettier support since I don't really like changing my IDE's tabs to actual tabs instead of spaces and having to put semicolon at the end of each line. Plus, you get consistent code formatting all over the project.

We're good with [XO](https://github.com/xojs/xo) 😄

File: lib/assert.js [hunk 1]
```diff
@@ -53,25 +53,21 @@ class AssertionError extends Error {
 		// Reserved for power-assert statements
 		this.statements = [];
 
-		if (opts.stack) {
-			this.stack = opts.stack;
+		if (opts.savedError && isError(opts.savedError)) {
```
Comment (novemberborn) [inline lib/assert.js]: Can't we assume `savedError` is an error?

File: lib/serialize-error.js [hunk 2]
```diff
@@ -51,6 +51,10 @@ function buildSource(source) {
 }
 
 function trySerializeError(err, shouldBeautifyStack) {
+	if (err.savedError) {
+		err.stack = err.savedError.stack;
```
Comment (novemberborn) [inline lib/serialize-error.js]: Don't modify `err`. Instead do something like:

```js
let stack = err.savedError ? err.savedError.stack : err.stack
if (shouldBeautifyStack) {
  stack = beautifyStack(stack)
}
```

File: lib/assert.js (hunk 1 above)
Comment (mihai-dinu) [reply lib/assert.js]: You're right. We don't pass in anything else other than an error as savedError. Will change it
