### PR TITLE
Only print fail-fast when there are remaining tests

### LINKED ISSUE #1171: Don't print --fail-fast reminder if no tests were actually skipped
With #1160 AVA now prints a reminder when `--fail-fast` is used and a test fails. Any number of tests could have been skipped.

If all other tests have indeed completed then the reminder is not necessary. A `remainingCount` could be computed and guarded against when printing the reminder, as described in https://github.com/avajs/ava/issues/1134#issuecomment-267961180.

### PR DESCRIPTION
**Pull request by jarlehansen**
This PR tries to fix #1171 by calculating the remaningCount in run-status.js
And then check the value in the reporters, if there are no remaining test it will not print:

> `--fail-fast` is on. Any number of tests may have been skipped

### CODE REVIEW

File: lib/run-status.js [hunk 1]
```diff
@@ -139,6 +140,7 @@ class RunStatus extends EventEmitter {
 		this.skipCount = sum(this.stats, 'skipCount');
 		this.todoCount = sum(this.stats, 'todoCount');
 		this.failCount = sum(this.stats, 'failCount');
+		this.remainingCount = (this.testCount - (this.passCount + this.failCount));
```
Comment (novemberborn) [inline lib/run-status.js]: `this.testCount - this.passCount - this.failCount` is clearer.

You need to include other test states in this count, see the highlighted lines in https://github.com/avajs/ava/blob/033d4dcdcbdadbf665c740ff450c2a775a8373dc/lib/run-status.js#L41:L45.

The computation should be tested. That's probably best in `test/run-status.js`, though most of its behavior ends up being tested elsewhere.

File: test/reporters/mini.js [hunk 2]
```diff
@@ -429,6 +430,18 @@ test('results when fail-fast is enabled', function (t) {
 	t.end();
 });
 
+test('results without fail-fast if no skipped tests', function (t) {
+	var reporter = miniReporter();
+	var runStatus = {
+		remainingCount: 0,
```
Comment (novemberborn) [inline test/reporters/mini.js]: I think this needs `failCount: 1`, like with the verbose test?

**Comment by jarlehansen** [comment]
Thanks for the comments, I will wait on #1177 to be merged and then update this PR.

**Comment by jarlehansen** [comment]
I have updated this PR with the changes done by @ThomasBem

File: lib/reporters/mini.js [hunk 3]
```diff
@@ -215,7 +215,7 @@ MiniReporter.prototype.finish = function (runStatus) {
 		});
 	}
 
-	if (runStatus.failFastEnabled === true) {
+	if (runStatus.failFastEnabled === true && runStatus.remainingCount > 0) {
```
Comment (novemberborn) [inline lib/reporters/mini.js]: This should check if there were any failures. Otherwise the warning is also printed when `.only()` is used and `--fail-fast` is on:

```
$ "$(npm bin)"/ava --fail-fast

  1 passed

  `--fail-fast` is on. Any number of tests may have been skipped

  The .only() modifier is used in some tests. 135 tests were not run.
```

**Comment by sindresorhus** [comment]
Thank you @jarlehansen. This is excellent 👌😄
