### PR TITLE
Fixes #2158: Ensure files passed through CLI exist, and are files

### LINKED ISSUE #2158: Ensure files passed through CLI exist, and are files, before precompiling
[Issuehunt badges](https://issuehunt.io/r/avajs/ava/issues/2158)

See #2156, where AVA was called with a test directory as its CLI argument (`ava test`). Precompilation fails because the "file" cannot be read. We should catch this and throw a more appropriate error.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#2184 [Wip]: Ensure files passed through CLI exist, and are files](https://issuehunt.io/r/avajs/ava/pull/2184)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/avajs/ava/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by MarchWorks**
Fixes #2158

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#2158: Ensure files passed through CLI exist, and are files, before precompiling](https://issuehunt.io/repos/26820798/issues/2158)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by MarchWorks** [comment]
I get it. This is not what I should do I will fix this now

**Comment by MarchWorks** [comment]
In which file should I add the tests

**Comment by MarchWorks** [comment]
Done

File: lib/cli.js [hunk 1]
```diff
@@ -270,6 +271,16 @@ exports.run = async () => { // eslint-disable-line complexity
 
 	const files = cli.input.map(file => path.relative(resolveTestsFrom, path.resolve(process.cwd(), file)));
 
+	for (const file of files) {
+		if (!fs.existsSync(file)) {
+			throw new Error(`No such file: ${cli.input[files.indexOf(file)]}`);
+		}
+
+		if (!fs.lstatSync(file).isFile()) {
```
Comment (novemberborn) [inline lib/cli.js]: I think this should use `statSync()`, since `lstatSync()` doesn't follow symlinks.

File: lib/cli.js [hunk 2]
```diff
@@ -270,6 +271,16 @@ exports.run = async () => { // eslint-disable-line complexity
 
 	const files = cli.input.map(file => path.relative(resolveTestsFrom, path.resolve(process.cwd(), file)));
 
+	for (const file of files) {
+		if (!fs.existsSync(file)) {
```
Comment (novemberborn) [inline lib/cli.js]: Using `statSync()` (see below) should be sufficient. It'll throw if the file (or its path) does not exist, but you can catch the error and use `error.code === 'ENOENT' || error.code === 'ENOTDIR'` to recognize whether the file existed. See https://nodejs.org/api/errors.html#errors_common_system_errors.

File: lib/cli.js [hunk 3]
```diff
@@ -270,6 +271,16 @@ exports.run = async () => { // eslint-disable-line complexity
 
 	const files = cli.input.map(file => path.relative(resolveTestsFrom, path.resolve(process.cwd(), file)));
```
Comment (novemberborn) [inline lib/cli.js]: Let's move this, and the validation, above the `new Api()` instantiation.

File: lib/cli.js [hunk 4]
```diff
@@ -270,6 +271,16 @@ exports.run = async () => { // eslint-disable-line complexity
...
 
+	for (const file of files) {
+		if (!fs.existsSync(file)) {
+			throw new Error(`No such file: ${cli.input[files.indexOf(file)]}`);
+		}
+
+		if (!fs.lstatSync(file).isFile()) {
+			throw new Error(`${cli.input[files.indexOf(file)]} should be a file`);
```
Comment (novemberborn) [inline lib/cli.js]: Use the `exit()` function instead.

File: lib/cli.js [hunk 5]
```diff
@@ -270,6 +271,16 @@ exports.run = async () => { // eslint-disable-line complexity
 
 	const files = cli.input.map(file => path.relative(resolveTestsFrom, path.resolve(process.cwd(), file)));
 
+	for (const file of files) {
+		if (!fs.existsSync(file)) {
+			throw new Error(`No such file: ${cli.input[files.indexOf(file)]}`);
```
Comment (novemberborn) [inline lib/cli.js]: Use the `exit()` function instead.

File: lib/cli.js (hunk 2 above)
Comment (MarchWorks) [reply lib/cli.js]: No need for `error.code === 'ENOTDIR'`

File: lib/cli.js [hunk 6]
```diff
@@ -214,6 +214,21 @@ exports.run = async () => { // eslint-disable-line complexity
...
+	const files = cli.input.map(file => path.relative(resolveTestsFrom, path.resolve(process.cwd(), file)));
+	for (const file of files) {
+		try {
+			const stats = fs.statSync(file);
+			if (!stats.isFile()) {
+				exit(`${cli.input[files.indexOf(file)]} should be a file`);
+			}
+		} catch (error) {
+			if (error.code === 'ENOENT') {
+				exit(`No sush file: ${cli.input[files.indexOf(file)]}`);
```
Comment (novemberborn) [inline lib/cli.js]: `such`

File: lib/cli.js [hunk 7]
```diff
@@ -214,6 +214,21 @@ exports.run = async () => { // eslint-disable-line complexity
...
+			}
+		}
```
Comment (novemberborn) [inline lib/cli.js]: You need to rethrow any other error.

Comment (MarchWorks) [reply lib/cli.js]: I used `throw new Error(error)` at first but I changed it to `exit` after. I am not sure which one is more appropriate in this case because this error is an unexpected one

**Comment by MarchWorks** [comment]
Done hopefully

File: lib/cli.js [hunk 8]
```diff
@@ -213,6 +214,23 @@ exports.run = async () => { // eslint-disable-line complexity
 
 	const match = arrify(conf.match);
 	const resolveTestsFrom = cli.input.length === 0 ? projectDir : process.cwd();
+
+	const files = cli.input.map(file => path.relative(resolveTestsFrom, path.resolve(process.cwd(), file)));
+	for (const file of files) {
+		try {
+			const stats = fs.statSync(file);
+			if (!stats.isFile()) {
+				exit(`${cli.input[files.indexOf(file)]} should be a file`);
```
Comment (novemberborn) [inline lib/cli.js]: Let's change this to:

```js
`${file} is not a test file.`
```

File: lib/cli.js [hunk 9]
```diff
@@ -213,6 +214,23 @@ exports.run = async () => { // eslint-disable-line complexity
...
+			}
+		} catch (error) {
+			if (error.code === 'ENOENT') {
+				exit(`No such file: ${cli.input[files.indexOf(file)]}`);
```
Comment (novemberborn) [inline lib/cli.js]: How about this?

```js
`${file} does not exist.`
```

File: lib/cli.js [hunk 10]
```diff
@@ -213,6 +214,23 @@ exports.run = async () => { // eslint-disable-line complexity
...
+			} else {
+				exit(`An unexpected error has occurred:\n${error}`);
```
Comment (novemberborn) [inline lib/cli.js]: Taking the lead from this line:

https://github.com/avajs/ava/blob/2fc7d56475ca1d77078abc3e08390341bedda58f/lib/cli.js#L145

How about:

```js
`Error accessing ${file}\n\n${chalk.gray((error && error.stack) || error)}`
```

File: lib/cli.js [hunk 11]
```diff
@@ -213,6 +214,23 @@ exports.run = async () => { // eslint-disable-line complexity
 
 	const match = arrify(conf.match);
 	const resolveTestsFrom = cli.input.length === 0 ? projectDir : process.cwd();
+
+	const files = cli.input.map(file => path.relative(resolveTestsFrom, path.resolve(process.cwd(), file)));
```
[the remark this answers is not in the document]
Comment (MarchWorks) [reply lib/cli.js]: Yes you are right I tested it they give the same output 
`[folder/filename]` from `cli.input` and `[folder\\filename]` from `files`

File: lib/cli.js (hunk 10 above)
Comment (MarchWorks) [reply lib/cli.js]: Yes better

**Comment by novemberborn** [comment]
@MarchWorks don't forget to update the tests for the new error messages 😉

**Comment by MarchWorks** [comment]
I completely forget that

File: lib/cli.js (hunk 11 above)
[the remark this answers is not in the document]
Comment (MarchWorks) [reply lib/cli.js]: @novemberborn seems that it's necessary it cause some tests to fail with node 8
https://travis-ci.org/avajs/ava/builds/564659393?utm_source=github_status&utm_medium=notification

[the remark this answers is not in the document]
Comment (MarchWorks) [reply lib/cli.js]: It fail on windows with node 8 most likely it has something to do with slash

[the remark this answers is not in the document]
Comment (novemberborn) [reply lib/cli.js]: Yes I realized it was existing code. I wrote it, too! Let’s keep it then.

[the remark this answers is not in the document]
Comment (MarchWorks) [reply lib/cli.js]: Then everything is done I think

**Comment by novemberborn** [comment]
Thanks @MarchWorks!

File: lib/cli.js [hunk 12]
```diff
@@ -213,6 +214,24 @@ exports.run = async () => { // eslint-disable-line complexity
...
+
+	for (const file of cli.input) {
```
Comment (ulken) [inline lib/cli.js]:
```suggestion
      for (const file of files) {
```

@novemberborn Right? If not, I suggest the mapping from `cli.input` to `files` move below this block (as before).

Comment (novemberborn) [reply lib/cli.js]: @ulken Yes good catch. Would you like to open a PR?

**Comment by ulken** [comment]
I’ve fixed it in my upcoming PR for #2138 (not unrelated fix, actually needed).

Should be ready for review soonish. I haven’t been able to work as much as I thought on it and ran in to a few bumps, but almost there now. Will open a PR when implementation is done and then do the docs if you want to start looking into it.

/Oskar
