### PR TITLE
prevent nested tests #948

### LINKED ISSUE #948: Nested test functions hide errors
## Description

I was just reviewing a PR where a colleague wrote tests in a nested way.

While the sub-tests never execute / show up in the test output they also did not create an error.

I would expect such code as the example below to at least throw an error.

### Test Source

```js
import test from 'ava';

test('outer', (t) => {

  test('innter', (t) => {
    t.fail();
    throw new Error('ERR');
  });

});
```

### Console Output

```sh
=> ./node_modules/.bin/ava -v avaTest.js

  ✔ outer

  1 test passed [16:35:53]
```

### Config

No config in package.json

### Command-Line Arguments

```
/ava -v avaTest.js
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v5.9.0
darwin 15.5.0
ava 0.15.2
npm 3.8.6
```

### PR DESCRIPTION
**Pull request by asafigan**
This is my first pull request so any feedback is welcome.

fixes #948 

Added a test in the runner test file which expects an error to be thrown when test is called in a test. I don't know if this is the right file to put this test, but it seem like a good place since my solution only changed the runner.js file.

My solution was to add a new property to runner called 'hasBegunRunning' which is set to true in the run method. The chaining function checks this property and throws an error when it is true.

I don't know if this is a good solution but it is simple and it works. Also, I don't know if I need more tests for this pull request.

### CODE REVIEW

File: lib/runner.js [hunk 1]
```diff
@@ -61,6 +62,10 @@ optionChain(chainableMethods, function (opts, args) {
 	var fn;
 	var macroArgIndex;
 
+	if (this.hasBegunRunning) {
+		throw new Error('Cannot have nested tests or hooks');
```
Comment (jamestalmage) [inline lib/runner.js]: This could also happen with:

```js
test(async t => {
  // stuff
});

setImmediate(() => {
  test(t => {
    // not allowed!
  });
});
```

The message should include something about declaring tests async.

> All tests and hooks must be declared synchronously in your test file, and cannot be nested within other tests.

**Comment by jamestalmage** [comment]
> I don't know if I need more tests for this pull request.

Add a second one that tests what I talked about [here](https://github.com/avajs/ava/pull/961#discussion_r70534537), and I think you are covered.

```js
// test
var r = new Runner();

r.test(() => Promise.resolve());
r.run()

t.throws(() => {
  r.test(() => {});
}, {message: ...})
```

> This is my first pull request

One of the best first PR's I have seen. Very good job. 🎉

**Comment by asafigan** [comment]
also I didn't know what type of error to throw

**Comment by asafigan** [comment]
Ok, I will add that test and also tweak the error message and the second test

**Comment by asafigan** [comment]
Ok I'm gone with those changes. Let me know if there is anything else I need to change.

**Comment by sotojuan** [comment]
👍 great job!

**Comment by asafigan** [comment]
thanks!

**Comment by jamestalmage** [comment]
LGTM

File: lib/runner.js [hunk 2]
```diff
@@ -46,6 +46,7 @@ function Runner(options) {
 
 	this.results = [];
 	this.tests = new TestCollection();
+	this.hasBegunRunning = false;
```
Comment (sindresorhus) [inline lib/runner.js]: I would use `isRunning` instead.

Comment (asafigan) [inline lib/runner.js]: I didn't name it is running because it isn't reset to true after the tests are done running.

Comment (asafigan) [inline lib/runner.js]: but I don't like `hasBegunRunning` either

Comment (sindresorhus) [inline lib/runner.js]: `hasStarted`?

Comment (asafigan) [inline lib/runner.js]: I like that better

Comment (sindresorhus) [inline lib/runner.js]: Let's go with that then.

**Comment by asafigan** [comment]
Ok, I changed the property name.

**Comment by asafigan** [comment]
Also should we mention in the docs somewhere that you shouldn't have embedded tests or hooks. And also that we have no alternative to describe.

**Comment by jamestalmage** [comment]
Thanks @asafigan!

> Also should we mention in the docs somewhere that you shouldn't have embedded tests or hooks. And also that we have no alternative to describe.

That probably belongs in a "transitioning from mocha/tape" recipe. Not sure it belongs in the core docs.

**Comment by asafigan** [comment]
woot! first contribution! 🎉
Thanks for all of the help on this

**Comment by sotojuan** [comment]
Awesome work @asafigan!

**Comment by sindresorhus** [comment]
Super first PR. Thanks @asafigan! Keep 'em coming ;)

68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f695054546a4574313969676e652f67697068792e676966
