### PR TITLE
Change serialization of Error summary due to #1995

### LINKED ISSUE #1995: Errors thrown outside of tests have truncated message
## Description

AVA is truncating multline error messages before displaying the error in the console when that error is thrown outside of a test (e.g. inside of a helper that is being imported). This doesn't seem to happen if the error is thrown in the test itself.

In the minimal example below, where AVA shows the source code lines with a hardcoded message, this may not seem like a big deal. But in practice, I stumbled upon this with some argument validation logic in a helper. The output in the terminal was super confusing and vague because the actual and exepected values were not on the first line (it was a [joi](https://github.com/hapijs/joi) error) and basically all it said was `ValidationError: {`.

### Test Source

```js
// test/hello-world.js
import test from 'ava';

throw new Error('I will be seen\nBut I will not be seen');

test('hello', () => {
    t.true(true);
});
```

### Error Message & Stack Trace

```
❯ npx ava test/hello-world.js


  ✖ No tests found in test/hello-world.js

  1 uncaught exception

  Uncaught exception in test/hello-world.js

  /Users/sholladay/Code/noirdoor/chords/test/hello-world.js:3

   2:
   3: throw new Error('I will be seen\nBut I will not be seen');
   4:

  Error: I will be seen
```

### Config

N/A

### Command-Line Arguments

```
npx ava
```

## Environment

```
Node.js v8.14.0
darwin 17.7.0
ava 1.0.0-rc.2
npm 6.4.1
```

### PR DESCRIPTION
**Pull request by CrispusDH**
1. Fixes #1995
2. Add `lines[index].startsWith('    at')` for fixing tests from `test/reports/*.js`
3. Change `skips esm enhancement lines when finding the summary` test in `test/serialize-error.js` for checking my changes
4. Firstly, I change `serialize standard props` test in in `test/serialize-error.js` 
from:
`t.is(serializedError.summary, 'Error: Hello');`
to:
`t.is(serializedError.summary, error.stack)`;
But after adding fix for `test/reports/*.js` I return it to initial 
`t.is(serializedError.summary, 'Error: Hello');` and it also pass

### CODE REVIEW

**Comment by CrispusDH** [comment]
@novemberborn or @sindresorhus , could you take a look at it? It's first PR in AVA so I'm not sure what are next steps

File: lib/serialize-error.js [hunk 1]
```diff
@@ -107,7 +107,16 @@ function trySerializeError(err, shouldBeautifyStack) {
 		} else {
 			// Skip the source line header inserted by `esm`:
 			// <https://github.com/standard-things/esm/wiki/improved-errors>
-			retval.summary = lines.find(line => !/:\d+$/.test(line));
+			const start = lines.indexOf(lines.find(line => !/:\d+$/.test(line)));
```
Comment (novemberborn) [inline lib/serialize-error.js]: You can use `findIndex()` for this.

**Comment by CrispusDH** [comment]
@novemberborn thanks for review, commit with requested change has been done :)

**Comment by novemberborn** [comment]
Thank you @CrispusDH.
