### PR TITLE
Not count hooks as tests

### LINKED ISSUE #2142: Hooks are counted as tests
[Issuehunt badges](https://issuehunt.io/r/avajs/ava/issues/2142)

When a hook fails it increases the count of tests:
```
not ok 23 - api › users › createUser › [C806006, monitoring, validation] Verify a user is created
not ok 25 - api › users › createUser › Delete test user for [C806006, monitoring, validation] Verify a user is created
```
**Delete test user** is a hook and it counted as a test, the current number of tests is 24, not 25

this is happening for verbose and tap formats

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $50.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($50.00)
### Submitted pull Requests
- [#2178 do not report failing hooks as test](https://issuehunt.io/r/avajs/ava/pull/2178)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/avajs/ava/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by yovasx2**
fixes #2142 
This contains specs modifications for #2178

### CODE REVIEW

**Comment by yovasx2** [comment]
@novemberborn @sindresorhus  please take a look

File: lib/reporters/tap.js [hunk 1]
```diff
@@ -118,6 +119,21 @@ class TapReporter {
 		}) + os.EOL);
 	}
 
+	writeLogs(evt, flags = {error: false, title: ''}) {
+		let formattedTitle = flags.title || this.prefixTitle(evt.testFile, evt.title);
+		if (flags.error) {
+			formattedTitle = `Failed hook: ${formattedTitle}`;
+		}
+
+		this.reportStream.write(`# ${stripAnsi(formattedTitle)}${os.EOL}`);
```
Comment (novemberborn) [inline lib/reporters/tap.js]: What's the reason for not using `supertap` here?

File: lib/reporters/tap.js [hunk 2]
```diff
@@ -118,6 +119,21 @@ class TapReporter {
 		}) + os.EOL);
 	}
 
+	writeLogs(evt, flags = {error: false, title: ''}) {
+		let formattedTitle = flags.title || this.prefixTitle(evt.testFile, evt.title);
```
Comment (novemberborn) [inline lib/reporters/tap.js]: This would be better as `writeLogs(evt, { error = false, title = this.prefixTitle(evt.testFile, evt.title) } = {})`.

File: lib/reporters/tap.js [hunk 3]
```diff
@@ -118,6 +119,21 @@ class TapReporter {
 		}) + os.EOL);
 	}
 
+	writeLogs(evt, flags = {error: false, title: ''}) {
```
Comment (novemberborn) [inline lib/reporters/tap.js]: In my mind, "logs" here refers to `evt.logs`, but that doesn't quite cover the scenarios in which it's called. What are you referring to? Should this be `writeTapComment()`?

File: lib/reporters/tap.js (hunk 1 above)
Comment (yovasx2) [reply lib/reporters/tap.js]: `supertap`'s API is just having **start**, **finish** and **test**, methods, I cannot use start or finish, the only remaining one is **test** but it's injecting prefix **(not)ok**, so it's counted as test, we need to modify supertap to have another method available called hook to just write the content of the hook without outputting the test format.

File: lib/reporters/tap.js (hunk 2 above)
Comment (yovasx2) [reply lib/reporters/tap.js]: I will use: `writeLogs(evt, { error = false, title = this.prefixTitle(evt.testFile, evt.title) }) {` without default value to prevent bad behavior, in that case if you don;t pass the object deconstruction fails and you are acknowledged

File: lib/reporters/tap.js (hunk 3 above)
Comment (yovasx2) [reply lib/reporters/tap.js]: I agree the proposed name is better, but since any function inside the reporter uses TAP, I will choose `writeComment`

File: lib/reporters/tap.js (hunk 1 above)
Comment (novemberborn) [reply lib/reporters/tap.js]: Fair enough. I suppose it'd be good to contribute a comment method to `supertap` but that's up to you.
