### PR TITLE
Fail hard when `--concurrency` is used without a value

### LINKED ISSUE #1367: --concurrency without value should fail
See https://github.com/avajs/ava/issues/1365#issuecomment-296146387. `--concurrency` requires a value but you can run AVA without specifying it.

### PR DESCRIPTION
**Pull request by yatharthk**
Fixes #1367

### CODE REVIEW

File: test/cli.js [hunk 1]
```diff
@@ -364,6 +364,14 @@ test('bails when config contains `"tap": true` and `"watch": true`', t => {
 	});
 });
 
+test('bails when config does not contain `--concurrency` and `-c` values', t => {
```
Comment (yatharthk) [inline test/cli.js]: @novemberborn This test fails with error below:

```
bails when config does not contain `--concurrency` and `-c` values
  not ok spawn /Users/yatharthk/.node-spawn-wrap-62339-36f9a5f0c8ca/node ENOENT
    at:
      line: 1026
      column: 11
      file: util.js
      function: exports._errnoException
    code: ENOENT
    errno: ENOENT
    syscall: spawn /Users/yatharthk/.node-spawn-wrap-62339-36f9a5f0c8ca/node
    path: /Users/yatharthk/.node-spawn-wrap-62339-36f9a5f0c8ca/node
    spawnargs:
      - ../../../cli.js
      - test.js
    test: bails when config does not contain `--concurrency` and `-c` values
```

I'm not really sure what's expected here. Can you also let me know if `{dirname: 'fixture/concurrency'}` is correct? I didn't understand how this works!

File: lib/cli.js [hunk 2]
```diff
@@ -118,6 +118,10 @@ exports.run = () => {
 		throw new Error(colors.error(figures.cross) + ' Watch mode is not available in CI, as it prevents AVA from terminating.');
 	}
 
+	if (hasFlag('--concurrency') || hasFlag('-c')) {
```
Comment (sindresorhus) [inline lib/cli.js]: This is not the correct way to check. AVA can be run with either `ava --concurrency=1` or `ava --concurrency 1`.

File: lib/cli.js [hunk 3]
```diff
@@ -118,6 +118,10 @@ exports.run = () => {
...
+		throw new Error(colors.error(figures.cross) + ' The --concurrency and -c flags must be provided the maximum number of test files to run with.');
```
Comment (sindresorhus) [inline lib/cli.js]: `the maximum number of test files to run with.` => `the maximum number of test files to run at once.`

File: lib/cli.js (hunk 2 above)
Comment (yatharthk) [inline lib/cli.js]: @sindresorhus I see. In that case, `((hasFlag('--concurrency') || hasFlag('-c')) && !cli.flags.concurrency)` should work good, right?

Comment (sindresorhus) [inline lib/cli.js]: No, that wouldn't work if the user had `concurrency` defined in package.json.

The correct check would be:

```js
if (cli.flags.concurrency === '') {
```

As it would be an empty string if the value is not defined, as we already define `concurrency` to be a string in the `meow` config.

Comment (yatharthk) [inline lib/cli.js]: Okay, okay. Thanks for explaining.

File: test/cli.js (hunk 1 above)
Comment (yatharthk) [inline test/cli.js]: @sindresorhus I read the test code in detail to understand how tests are written for `cli`! Do we need to write it in a similar way as we do for `watcher` et al? Any specific cases to cover?

cc/ @novemberborn

Comment (novemberborn) [inline test/cli.js]: These tests can be hard to get right. I'd start with running the CLI directly (`node cli.js test/fixture/concurrency/test.js` etc) to make sure it works correctly. Then try invoking it from the test.

Comment (yatharthk) [inline test/cli.js]: @novemberborn This works! Can you tell me what all cases to cover in `test/fixture/concurrency/test.js` ?

Comment (novemberborn) [inline test/cli.js]: CLI invocation with `--concurrency` and `-c` without a value. Presumably there are tests where a value *is* provided, but if not those should be added.

File: test/cli.js [hunk 4]
```diff
@@ -364,6 +364,25 @@ test('bails when config contains `"tap": true` and `"watch": true`', t => {
 	});
 });
 
+['--concurrency', '-c'].forEach(concurrencyFlag => {
+	test(`bails when ${concurrencyFlag} provided without value`, t => {
+		execCli([concurrencyFlag, 'test.js'], {dirname: 'fixture/concurrency'}, (err, stdout, stderr) => {
+			t.is(err.code, 1);
+			t.match(stderr, 'The --concurrency and -c flags must be provided the maximum number of test files to run at once.');
```
Comment (yatharthk) [inline test/cli.js]: @novemberborn This test doesn't seem to pass. Can you see any  fault in the `match()`?

File: test/cli.js [hunk 5]
```diff
@@ -364,6 +364,25 @@ test('bails when config contains `"tap": true` and `"watch": true`', t => {
...
+			t.end();
+		});
+	});
+});
+
+['--concurrency', '-c'].forEach(concurrencyFlag => {
```
Comment (yatharthk) [inline test/cli.js]: @novemberborn This tests for success if the value is provided for the flags. Looks good?

File: test/cli.js (hunk 4 above)
Comment (novemberborn) [inline test/cli.js]: What does `stderr` actually contain?

I had some trouble running this directly from the command line, it seemed to start running TAP tests instead. Try `execCli(['test.js', concurrencyFlag], …)` instead.

File: test/cli.js [hunk 6]
```diff
@@ -364,6 +364,25 @@ test('bails when config contains `"tap": true` and `"watch": true`', t => {
 	});
 });
 
+['--concurrency', '-c'].forEach(concurrencyFlag => {
+	test(`bails when ${concurrencyFlag} provided without value`, t => {
+		execCli(['test.js', concurrencyFlag], {dirname: 'fixture/concurrency'}, (err, stdout, stderr) => {
```
Comment (yatharthk) [inline test/cli.js]: @novemberborn Thanks. Tests pass now. :)

cc/ @sindresorhus

**Comment by yatharthk** [comment]
@novemberborn Any progress on this?  cc/ @sindresorhus

**Comment by sindresorhus** [comment]
Looks good. Thank you @yatharthk :)

**Comment by yatharthk** [comment]
@sindresorhus @novemberborn Happy to contribute :)
